name: "units-test"
on:
  push:
    branches:
      - '*'

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        sendkey: ${{ secrets.SCKEY }}
        text: testok
        desp: ok
